include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/l10n/generated/**
    - "**/*.g.dart"
    - functions/**
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    avoid_print: true
